// Usage: node scripts/trace-silhouette.mts
// Traces the alpha edge of the Goran plates into vector paths (viewBox 800×1600),
// so the ink contour stays 1 px on screen at any zoom. Output: src/atlas/figure/silhouette.ts
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { decodePngAlpha, type PngAlpha } from "../tests/pngAlpha.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Same rects as BODY_PLATE in src/atlas/figure/Figure.tsx (xMidYMid meet). */
const PLATES = {
  anterior: { x: 97.61, y: 40, width: 604.79, height: 1440, file: "public/atlas/body-anterior.png" },
  posterior: { x: 97.47, y: 40, width: 605.06, height: 1440, file: "public/atlas/body-posterior.png" },
} as const;

const THRESHOLD = 127;
const EPSILON_PX = 0.9;
const MIN_LOOP_PX = 40;

type P = [number, number];

function inside(img: PngAlpha, x: number, y: number): number {
  if (x < 0 || y < 0 || x >= img.width || y >= img.height) return 0;
  return (img.alpha[y * img.width + x] ?? 0) > THRESHOLD ? 1 : 0;
}

/** Marching squares over the pixel grid. Edge midpoints are keyed on a doubled grid. */
function loops(img: PngAlpha): P[][] {
  const adj = new Map<number, number[]>();
  const W2 = img.width * 2 + 4;
  const key = (x2: number, y2: number) => (y2 + 2) * W2 + (x2 + 2);
  const link = (a: number, b: number) => {
    (adj.get(a) ?? adj.set(a, []).get(a)!).push(b);
    (adj.get(b) ?? adj.set(b, []).get(b)!).push(a);
  };
  for (let y = -1; y < img.height; y += 1) {
    for (let x = -1; x < img.width; x += 1) {
      const tl = inside(img, x, y);
      const tr = inside(img, x + 1, y);
      const br = inside(img, x + 1, y + 1);
      const bl = inside(img, x, y + 1);
      const c = (tl << 3) | (tr << 2) | (br << 1) | bl;
      if (c === 0 || c === 15) continue;
      const T = key(2 * x + 1, 2 * y);
      const R = key(2 * x + 2, 2 * y + 1);
      const B = key(2 * x + 1, 2 * y + 2);
      const L = key(2 * x, 2 * y + 1);
      switch (c) {
        case 1: case 14: link(L, B); break;
        case 2: case 13: link(B, R); break;
        case 3: case 12: link(L, R); break;
        case 4: case 11: link(T, R); break;
        case 6: case 9: link(T, B); break;
        case 7: case 8: link(L, T); break;
        case 5: link(L, T); link(B, R); break;
        case 10: link(T, R); link(L, B); break;
      }
    }
  }
  const seen = new Set<number>();
  const out: P[][] = [];
  const toPoint = (k: number): P => [((k % W2) - 2) / 2 + 0.5, (Math.floor(k / W2) - 2) / 2 + 0.5];
  for (const start of adj.keys()) {
    if (seen.has(start)) continue;
    const loop: P[] = [];
    let prev = -1;
    let cur = start;
    while (!seen.has(cur)) {
      seen.add(cur);
      loop.push(toPoint(cur));
      const next = (adj.get(cur) ?? []).find((n) => n !== prev && !seen.has(n));
      if (next === undefined) break;
      prev = cur;
      cur = next;
    }
    if (loop.length >= MIN_LOOP_PX) out.push(loop);
  }
  return out;
}

function rdp(pts: P[], eps: number): P[] {
  if (pts.length < 3) return pts;
  const [ax, ay] = pts[0]!;
  const [bx, by] = pts[pts.length - 1]!;
  const len = Math.hypot(bx - ax, by - ay) || 1;
  let best = -1;
  let far = 0;
  for (let i = 1; i < pts.length - 1; i += 1) {
    const [px, py] = pts[i]!;
    const d = Math.abs((bx - ax) * (ay - py) - (ax - px) * (by - ay)) / len;
    if (d > far) {
      far = d;
      best = i;
    }
  }
  if (far <= eps) return [pts[0]!, pts[pts.length - 1]!];
  return [...rdp(pts.slice(0, best + 1), eps).slice(0, -1), ...rdp(pts.slice(best), eps)];
}

function toPath(view: keyof typeof PLATES): { d: string; points: number; loops: number } {
  const plate = PLATES[view];
  const img = decodePngAlpha(join(root, plate.file));
  const s = Math.min(plate.width / img.width, plate.height / img.height);
  const ox = plate.x + (plate.width - img.width * s) / 2;
  const oy = plate.y + (plate.height - img.height * s) / 2;
  let points = 0;
  const all = loops(img);
  const parts = all.map((loop) => {
    const mid = Math.floor(loop.length / 2);
    const simple = [...rdp(loop.slice(0, mid + 1), EPSILON_PX).slice(0, -1), ...rdp(loop.slice(mid).concat([loop[0]!]), EPSILON_PX).slice(0, -1)];
    points += simple.length;
    return (
      "M" +
      simple.map(([x, y]) => `${(ox + x * s).toFixed(1)} ${(oy + y * s).toFixed(1)}`).join("L") +
      "Z"
    );
  });
  return { d: parts.join(""), points, loops: all.length };
}

const a = toPath("anterior");
const p = toPath("posterior");
const file = join(root, "src/atlas/figure/silhouette.ts");
writeFileSync(
  file,
  `/** Generated by scripts/trace-silhouette.mts from the Goran plates. Do not edit by hand. */\n` +
    `export const SILHOUETTE = {\n  anterior: "${a.d}",\n  posterior: "${p.d}",\n} as const;\n`,
);
console.log(`anterior loops=${a.loops} points=${a.points} · posterior loops=${p.loops} points=${p.points} → ${file}`);
